# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.11-slim

# Install system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    libxml2-dev \
    libxslt-dev \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy requirements and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy source code
COPY . .

# Patch ExperimentalCapabilities usage to pass empty dict
RUN sed -i 's/experimental_capabilities=ExperimentalCapabilities()/experimental_capabilities={}/g' src/server.py

# Default command
CMD ["python", "-m", "src.server"]
